### ISSUE TITLE
Add node_modules/ to .gitignore

### ISSUE THREAD

**Issue by ojdon** [rapidwebltd/gulp-workflow#2]
Also create a .gitignore file, if one does not already exist.

**Comment by Jord-JD** [comment]
```
echo "node_modules/" >> ".git_ignore"
```

**Comment by jbrooksuk** [comment]
FWIW ignore lines like this should be within a global gitignore, rather than a project level.

**Comment by ojdon** [comment]
@jbrooksuk Agreed. But is there a problem with having it on a project level as well? Just in case users don't have it defined on a global level.
